### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by yyf17** [pathak22/hierarchical-imitation#1]
I have a  question, could you help me?

from model import inverse_model,the package or module "model" is not in your code base

**Comment by pratyushasharma** [comment]
Updated. Thanks for letting us know.

**Comment by v-bengbeng-v** [comment]
> 我有一个问题，你能帮我吗？
> 
> 从模型导入 inverse_model，包或模块“模型”不在您的代码库中

请问您的pix2pix网络模型跑通了吗?我的为什么总是出现通道错误.
-----------------------------------------------
Setting up a new session...
create web directory ./checkpoints/robot_pix2pix/web...
ra torch.Size([1, 12, 256, 256])
Traceback (most recent call last):
  File "train.py", line 32, in <module>
    model.optimize_parameters()
  File "/home/zhanghao/PycharmProjects/hierarchical-imitation/pix2pix/models/pix2pix_model.py", line 113, in optimize_parameters
    self.backward_D()
  File "/home/zhanghao/PycharmProjects/hierarchical-imitation/pix2pix/models/pix2pix_model.py", line 84, in backward_D
    pred_real = self.netD(real_AB)
  File "/home/zhanghao/anaconda3/envs/py/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhanghao/PycharmProjects/hierarchical-imitation/pix2pix/models/networks.py", line 358, in forward
    return self.model(input)
  File "/home/zhanghao/anaconda3/envs/py/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhanghao/anaconda3/envs/py/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/zhanghao/anaconda3/envs/py/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhanghao/anaconda3/envs/py/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [64, 6, 4, 4], expected input[1, 12, 256, 256] to have 6 channels, but got 12 channels instead
