### ISSUE TITLE
Do not find subsample.py

### ISSUE THREAD

**Issue by yikaiw** [pathak22/hierarchical-imitation#3]
Nice work, but I do not find the file subsample.py (as mentioned in your README) in the code base, and thus trajectories cannot be generated.  Could you please make an update for subsample.py? Thank you.

**Comment by v-bengbeng-v** [comment]
> 干得好，但我在代码库中找不到文件 subsample.py（如您的自述文件中所述），因此无法生成轨迹。你能更新 subsample.py 吗？谢谢你。

Hello,did you achieve this project?

**Comment by yikaiw** [comment]
Stopped trying then.

**Comment by v-bengbeng-v** [comment]
Haven't you tried this?utils.py?

**Comment by v-bengbeng-v** [comment]
> 然后就停止尝试了。

Haven't you tried this?utils.py?

**Comment by v-bengbeng-v** [comment]
> 干得好，但我在代码库中找不到文件 subsample.py（如您的自述文件中所述），因此无法生成轨迹。你能更新 subsample.py 吗？谢谢你。

代码里的pix2pix网络模型您跑通了吗?我的老是报出通道错误
-----------------------------------------------
Setting up a new session...
create web directory ./checkpoints/robot_pix2pix/web...
ra torch.Size([1, 12, 256, 256])
Traceback (most recent call last):
  File "train.py", line 32, in <module>
    model.optimize_parameters()
  File "/home/zhanghao/PycharmProjects/hierarchical-imitation/pix2pix/models/pix2pix_model.py", line 113, in optimize_parameters
    self.backward_D()
  File "/home/zhanghao/PycharmProjects/hierarchical-imitation/pix2pix/models/pix2pix_model.py", line 84, in backward_D
    pred_real = self.netD(real_AB)
  File "/home/zhanghao/anaconda3/envs/py/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhanghao/PycharmProjects/hierarchical-imitation/pix2pix/models/networks.py", line 358, in forward
    return self.model(input)
  File "/home/zhanghao/anaconda3/envs/py/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhanghao/anaconda3/envs/py/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/zhanghao/anaconda3/envs/py/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhanghao/anaconda3/envs/py/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [64, 6, 4, 4], expected input[1, 12, 256, 256] to have 6 channels, but got 12 channels instead

您遇到过这种情况吗?
